### ISSUE TITLE
connection issues, screen tearing

### ISSUE THREAD

**Issue by FoxbitDreamtail** [yawut/ntrview-wiiu#4]
I changed a few settings in the config ini file to get a better picture and then uppon connecting, the right sides of the wiiu glitch out, the 3ds is fine however. the longer it stayed connected the worse ot got....  however when there is a picture it is clearer, sucssess I guess? my guess is that it is a cache error.... I will keep trying different web sockets to see if that fixes it.

**Comment by QuarkTheAwesome** [comment]
Increasing picture quality also increases the number of packets needed to send it, which would usually be fine except my netcode is kinda crap and doesn't handle packet loss well. so if you have a shaky WiFi link *and* you've cranked the image quality it's likely to act up like this. all I can really suggest right now is turning the quality back down or getting on a better WiFi link

**Comment by FoxbitDreamtail** [comment]
just a suggustion for the next update is to optimize that netcode and to add more settings to the left stick click menu.
