### ISSUE TITLE
ntrview not connecting to old 3DS model?

### ISSUE THREAD

**Issue by AC-Drift** [yawut/ntrview-wiiu#7]
I've just recently got Boot NTR on my 3DS xl and for some reason ntrview can't seem to connect even though I put in the 3DS's IP address. so I'm wondering if the Boot NTR on New 3DS models is different then Old 3DS models? (for reference I'm using "Boot NTR Selector Mode 3 - Enhanced NTR CFW Loader" on it if that makes any difference) I'm just confused

**Comment by AC-Drift** [comment]
never mind I found out that Boot NTR doesn't even work properly on old models (those tutorials lied to me) sorry to waste your time

**Comment by QuarkTheAwesome** [comment]
Yeah, sadly not possible on Old 3DS. Which tutorials are telling ya that? I’ve been seeing more interest in ntrview than usual and am wondering if we got mentioned somewhere..

**Comment by AC-Drift** [comment]
so far I haven't found anyone who mention your program but I did mention it to my friend who wasn't able to use (or at least have a good experience with) stickerstream because of his low powered PC, I'm sure he'll enjoy it once he get a chance to mess with his Wii U but keep up the good work!!! I'll be sure to check the program out once I get my new 2DS xl in the mail :)
